### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by Luanter** [zehmaria/barely-an-assembly#4]
lastest version, patchouli questbook simply wont work 
![image](https://user-images.githubusercontent.com/110932411/205346832-b66b8d12-1e5b-44a4-ac4e-152ca3247c7d.png)
ftb questbook still exists , you dont spawn with it and ftb buttons disappeared from gui, so you have no clue that it exists until you get a log

Another issue is, even if you get to tinkers (getting resources on the world to make a better pick,getting torches from villages and boats to get bricks et cetera.), you need copper plates to make a drain, and to make a plate you need a press.. and to make the press you need to drain andesite alloy..
![image](https://user-images.githubusercontent.com/110932411/205349208-b17edc97-c29a-49ee-8eb8-7886b46678e7.png)

last issue i had is massive lag for random things like villagers 
![image](https://user-images.githubusercontent.com/110932411/205349552-9b849837-88e1-426e-bed6-c55d582b0cea.png)

**Comment by zehmaria** [comment]
I uploaded a new version with some fixes, it should be approved soon. 

- I had forgotten to include the patchouli folder in the export... That was a silly mistake! It should load now. 
- I also changed to give the fbt quest book when the player login, together with the other items. 
- The Drain recipe uses raw copper now. Thanks for the heads up. 
- However, for the village issue, I couldn't really pinpoint it easily. I couldn't spawn a village with +1000. I tried removing some mods that might cause an issue but I've seen no difference, either. I did add the mod Canary, the latest port of lithium. But I'm always a bit weary of including it since it often breaks with modded mobs. It did help though with the average, at first glance. I'll do a few more tests later and see if I can find anything else. If you can let me know if you've seen anything else causing that much lag, that might help. Also, try to see if that happens somewhere else, or if it's something in that place that's making it's AI code crazy. I did hear before about villagers lagging due to trying to find a way to a bed or a profession block, but not being able to reach it or something similar. 

Thanks for the feedback.
