### ISSUE TITLE
Issues v2 

### ISSUE THREAD

**Issue by Luanter** [zehmaria/barely-an-assembly#5]
Sup :) new version new problems

1: not really a problem, i feel that oneprobe readme should be given to player, i personally dont like my probe to be bottom left and wanted to alter.
2: trying to get the one probe readme, activated cheat mode on JEI, it doesnt seem to work properly, did you change any keys for it?
2.1: Also regarding to JEI, it asks for configured mod to acess the ingame config.
3: Villager lag issue not solved, no clue whats causing. https://www.reddit.com/r/technicalminecraft/comments/toyvlh/massive_and_i_mean_massive_lags_caused_by_my/
"Turn off the fresh animations resource pack. I had the same issue." maybe try that.
4: Not really a problem 2: sticks are a pain to get before the saw, maybe add an farmer´s deligth flint knife that drops sticks from three leaves.
5: The only option of pick we get is the wooden, cant mine ores, cant progress. 
5.1:  Got planks from a village to try and craft an stone tinkers pick, turns out that tinkers is broken, tools wont go in the slot, table icons invis, and you cant see but there is a broken axe on the dust slot. impossible to progress as it is.
![image](https://user-images.githubusercontent.com/110932411/205493250-63703f1b-8135-4ef9-97b3-a992f44b781d.png)
7: Also stock tools are having a mess with tags it keeps coming down like a waterfall
![image](https://user-images.githubusercontent.com/110932411/205493323-af3fb361-2fdc-4d3e-b776-c93827de9362.png)
8: tinkers station quests only unlock after andesite casing, impossible to get there before using it (maybe tools are made of flint solves it) 
8.1 also regarding to quests "automation" quest tab seems to be off center? you have to keep pulling it everytime you open.
![image](https://user-images.githubusercontent.com/110932411/205493706-031c1292-d7b4-40f9-8696-cc8cc83c2eb8.png)

until next time zeh 👍

**Comment by zehmaria** [comment]
Hello, again!

1.  I'm giving it by default again. 
2.  It works here, but I did notice the config for hovering+number to make it place on inventory was disabled somehow [I had enabled it before since it's not on by default anymore]. Perhaps, is it that? I did not include configured by default since I don't use it, but I can. I also didn't include it because Create allows access for mod configuration too, but perhaps that's too obscure, so I'm adding configured. 
3. I don't have that resource pack. And I try to avoid any mod that sounds too good since the "good" looking/interactions often have a high cost. I tested it, and most village has around 100/t. Some have 150. But I can't get 1000. And I did a test with no mods too, only forge+Observable, and it was around that amount [slightly higher]. So, idk.
4. Using TC Axes now gives you sticks often. I added a tooltip to explain that. Just try to break the blocks. 
5.  I've increased the wooden mining level to be the same as stone. It can mine iron now, and I've decreased stats slightly as a counterbalance. 
6.  Numismatic Overhaul: Reforged was breaking TC UI, I've removed it. I wouldn't have expected it to cause that. I added it not that long ago too. Stuff now works again. 
7. I've disabled tags by default now. That was JEintegration. You can still access nbt when debug mode is on. 
8.  With the change for the wooden pick, you should now be able to make Andesite Alloy. 
9. It does "center," but it takes into consideration every quest, even the hidden ones. It doesn't remember the prior placement, either. The page just got a bit too big, and I had tried to spread them too much. I tried making it more compact for now, and let's see if that's fine. If you still find it to be too annoying, let me know, and I'll try to break the tab into two. That's the only other way I can think. From now on when doing those pages, I'll keep that in mind too since it's very annoying indeed.

Thank you for helping with the testing!
