### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by Luanter** [zehmaria/barely-an-assembly#7]
new version, no quests 
![image](https://user-images.githubusercontent.com/110932411/206193101-b8e635fd-ed92-459d-8e90-cb6328a3f761.png)

**Comment by Luanter** [comment]
also, dried kelp blocks have no recipe, needed on hose pulley

**Comment by zehmaria** [comment]
Yesterday I tested a new instance, and it worked. Today, I tried to install an older version first and then updated it. While the quest remained, the key binds did not. It should be an issue in adding DefaultSettings to an already configured instance. 

While I was configuring that mod, I did notice it making the Pollution of Realms config disappear once, that might be related too. But I couldn't pinpoint exactly what caused it, and I didn't see it happening again. 

The Ftbquest folder will be included in the normal level because it changes so much and the player shouldn't interact with it, so that will solve your issue. However, that change might have impacted something else. 

If you don't want to bother with a new instance, you can delete .minecraft/ds_private_storage.json and all other configs [in the config folder] aside from [defaultsettings folder, defaultsettings.json, and ftbquests folder]. It should populate the configs right this time, and I'm hoping those issues won't happen again, but I'm monitoring it in a separate instance this time. 

I don't think I'm misusing that mod, but that could also be it. I'll see once the update is approved, if the changes I made stick as I expect or not.

**Comment by zehmaria** [comment]
I went middle ground. I did the default thingy for options and keys, but left the configs alone. That seems to be what the big people are doing in 1.18 too [Enigmatic and ATM]. I think that should be fine.
